project:
  render:
    - Thesis.qmd

title: "Parallel Classification using Support Vector Machines on Modern GPUs"
subtitle: |
    | Πανεπιστήμιο Δυτικής Αττικής
    | \includegraphics{./img/logo.jpg}
    | Τμήμα Μηχανικών Πληροφορικής και Υπολογιστών
date: now
date-format: dddd MMMM D, YYYY
# author: Ευάγγελος Κατσανδρής (cs171014@uniwa.gr)
author:
  - name: Ευάγγελος Κατσανδρής
    # id: jc
    # orcid: 0000-0002-1825-0097
    email: cs171014@uniwa.gr
    affiliation: 
      - name: University of West Attica
        city: Athens
        department: Computer Engineering and Informatics
        # state: RI
        url: www.uniwa.gr
# abstract: > 
#   This is the abstract words. Another sentence.
# thanks: > 
#   This is the thanks section. Sentence two!
license: "CC BY"
copyright: 
  holder: Ευάγγελος Κατσανδρής
  year: 2024
# citation: 
#   container-title: Journal of Psychoceramics
#   volume: 1
#   issue: 1
#   doi: 10.5555/12345678
funding: "The author received no specific funding for this work."

glossary:
  path: glossary.yml
  popup: none
  show: true
format:
    wordcount-pdf:
        # template: /home/evan/.pandoc/templates/eisvogel.latex
        # template: /home/evan/.pandoc/templates/new.latex # rec
        # template: ./template.latex
        toc: false
        number-depth: 3
        number-sections: true
        # listings: true
        include-in-header: # ok
            - file: packages.tex
            - file: macros.tex
        keep-tex: true # ok
        latex-auto-install: false
        # pandoc-args: "--lua filter ./filters/minted.lua"
        # pdf-engine-opt: "-shell-escape"
        cite-method: biblatex # ok
        documentclass: scrreprt # ok ?
        # documentclass: report # ok ?
        geometry: margin=2.54cm
        papersize: a4 # ok
        fontsize: 11pt # ok
        mainfont: Liberation Serif # ok
        sansfont: Liberation Sans # ok
        # monofont: Source Code Pro # ok
        monofont: Monaspace Neon
        linestretch: 1.5 # ok
        linkcolor: uniwablue
        urlcolor: uniwablue
        citecolor: uniwaorange
        # code-line-numbers: true
        highlight-style: github
        code-block-border-left: "#123c64"
        code-block-bg: "#e5e6ee"

# output: 
#     pdf:
lang: en # rec
# language: ./_language-el.yml # delete when quarto 1.4 is released :3

bibliography: bibliography.bib
biblio-style: ieee
biblatexoptions: sorting=none
nocite: |
  @R, @tidyr, @ggplot, @scales, @quarto

# latex-auto-mk: false

############
# eisvogel #
############
#
# code-block-font-size: \footnotesize
# table-use-row-colors: true
# titlepage: true
# titlepage-rule-color: 123c64 # #123c64
# titlepage-rule-height: 10
# caption-justification: centering
# toc-own-page: false

# RELEASE_URL=https://github.com/pandoc/lua-filters/releases/latest
#curl -LSs $RELEASE_URL/download/lua-filters.tar.gz | \
#    tar --strip-components=1 --one-top-level=$PANDOC_DIR -zvxf -
