

<!-- titlepage -->

\newpage

<!-- empty page -->

\newpage

<!-- info page -->

\newpage

<!-- empty page -->

\newpage

<!-- δήλωση συγγραφέα -->

\newpage

<!-- empty page -->

\newpage

<!-- ευχαριστίες -->

\newpage

<!-- empty page -->

\newpage

<!-- abstract -->
# Επισκόπηση του πεδίου, προσδιορισμός του προβλήματος και διεθνής εμπειρία

* Να προσδιορίζεται η ουσία του προβλήματος της ΔΕ,
* Να αξιοποιείται και να αναφέρεται η σχετική βιβλιογραφία, θεωρία, πηγές, μέθοδοι και
μεθοδολογία,
* Να χρησιμοποιούνται θεωρητικά και πρακτικά παραδείγματα και υποδείγματα για την
τεκμηρίωση των θέσεων,
* Να αποφεύγονται επαναλήψεις,
* Να παρουσιάζονται τα δεδομένα της επισκόπησης με συγκριτική και κριτική λογική,
* Να συνδέονται τα ευρήματα της επισκόπησης με τις επιλογές και τα επόμενα βήματα της
εργασίας. 

# Μεθοδολογία και εργαλεία

Η ενότητα αυτή περιλαμβάνει τη γενική μεθοδολογική προσέγγιση (αναλυτική, εμπειρική, πειραματική,
κλπ.) και τις συγκεκριμένες μεθόδους που υιοθετήθηκαν και χρησιμοποιήθηκαν στην εργασία.
Αναφέρονται αναλυτικά όλα τα βήματα κάθε μεθόδου που ακολουθήθηκε, όπως αποφάσεις που
ελήφθησαν, αποκλεισμός ή ενσωμάτωση μεθοδολογικών προσεγγίσεων, χρονικά πλαίσια στα οποία
υλοποιήθηκε το εμπειρικό/πρακτικό/εργαστηριακό μέρος, ποσοτικοί δείκτες που υιοθετήθηκαν ή
δημιουργήθηκαν για μετρήσεις, συνθήκες πειραμάτων, παράμετροι, περιβάλλον, κ.λπ.

Στη μεθοδολογία πρέπει να παρουσιάζονται επίσης πληροφορίες για (α) τις πηγές των στοιχείων και
δεδομένων και (β) τα ειδικά εργαλεία, εξοπλισμό ή πακέτα λογισμικού που χρησιμοποιήθηκαν. Αυτό
θα επιτρέψει την επαναληψιμότητα των πειραμάτων και τη δυνατότητα επαλήθευσης των
αποτελεσμάτων της εργασίας από τον ενδιαφερόμενο αναγνώστη. 

# Τεχνικό Μέρος: Ανάλυση του προβλήματος και σύνθεση λύσης

Η ενότητα αυτή (ένα ή περισσότερα κεφάλαια) αποτελεί τον πυρήνα της συνεισφοράς του φοιτητή
στην επίλυση του προβλήματος. Περιλαμβάνει την ανάλυση του προβλήματος σε επιμέρους
ερωτήματα ή στάδια ή υποθέσεις προς έλεγχο, τις προδιαγραφές των αποδεκτών λύσεων καθενός, τη
σχεδίαση και υλοποίηση των επιμέρους λύσεων και τελικά τη σύνθεση της συνολικής λύσης στο αρχικά
τεθέν πρόβλημα.
Η περιγραφή της λύσης μπορεί να γίνεται σε επίπεδο πρότασης (νέας) μεθόδου ή εργαλείου,
συνδυασμό υπαρχουσών λύσεων για ένα νέο πρόβλημα, σχεδίαση σε επίπεδο συστήματος ή/και
υποσυστημάτων ή/και διατάξεων, προσομοίωση, ανάπτυξη / κατασκευή, ολοκλήρωση και λειτουργικό
έλεγχο πρωτοτύπου, ανάπτυξη κώδικα ή εφαρμογής λογισμικού.

Σημαντικό είναι να περιγραφούν αναλυτικά

* Η συγκέντρωση / ανάκτηση / εντοπισμός των απαραίτητων δεδομένων, η επεξεργασία
τους και η ανάλυση των αποτελεσμάτων,
* Τα ίδια τα αποτελέσματα οργανωμένα κατά πειράματα / υποθέσεις / περιπτώσεις και
επιμέρους συνθήκες/παραμέτρους, με σχήματα, πίνακες, διαγράμματα, κλπ. εποπτικά
μέσα,
* Σχολιασμός και προσπάθεια ερμηνείας των αποτελεσμάτων σε συσχέτιση με το
διερευνούμενο πρόβλημα αλλά και σε σύγκριση με γνωστά αποτελέσματα άλλων
λύσεων στο ίδιο πρόβλημα (από τη βιβλιογραφία). 

# Συμπεράσματα

Τα Συμπεράσματα αποτελούν το τελευταίο αριθμημένο κεφάλαιο του κειμένου και την κατακλείδα της
εργασίας. Εδώ συνοψίζονται ο στόχος, τα βήματα και τα αποτελέσματα της εργασίας, τονίζονται τα
ισχυρά / σημαντικά σημεία της και καταγράφονται οι δυσκολίες, περιορισμοί, ατέλειες ή αδυναμίες
της. Διατυπώνονται σαφώς οι απαντήσεις που προέκυψαν κατά την επεξεργασία του θέματος στα
ερωτήματα / προβλήματα που είχαν τεθεί αρχικά. Σχολιάζεται η συνολική πορεία της εργασίας και τα
θέματα που έμειναν ανοικτά προς περαιτέρω διερεύνηση ή ανάπτυξη, και προτείνονται κατευθύνσεις
για μελλοντικές επεκτάσεις. Τα Συμπεράσματα συνήθως έχουν έκταση 2-3 σελίδων. 

# Μορφοποίηση του κειμένου της Διπλωματικής Εργασίας

### Κείμενο:

* Το μέγεθος της σελίδας είναι Α4.
* Η γραμματοσειρά είναι Times New Roman σε μέγεθος 11 στιγμών.
* Το διάστιχο μεταξύ γραμμών είναι 1,5 γραμμή.
* Το μέγεθος γραμματοσειράς των επικεφαλίδων είναι 14 στιγμών, ενώ των υποκεφαλίδων είναι 12
στιγμών. Οι επικεφαλίδες και υποκεφαλίδες καλό είναι να είναι με έντονη γραφή (bold).
* Δεν πρέπει να υπάρχουν κενές γραμμές μεταξύ των παραγράφων. Η απόσταση ρυθμίζεται από το
διάστημα στην επιλογή «Παράγραφος» (paragraph). Ρυθμίζετε το διάστημα “πριν” των
παραγράφων ανάλογα: 0 ή 3 ή 6 ή 9.
* Ρυθμίζετε τον τίτλο του κεφαλαίου να έχει στυλ επικεφαλίδας με αρίθμηση. Επίσης ρυθμίζετε
έντονη γραφή, μέγεθος 14, διάστημα “πριν” και “μετά” 12 στιγμών.
* Δηλώνετε αλλαγή σελίδας με τη δημιουργία κάθε νέου κεφαλαίου (κάθε νέο κεφάλαιο αρχίζει
πάντα στην κορυφή νέας σελίδα).
* Κάθε κεφάλαιο έχει υποενότητες. Ομοίως ανάλογα ρυθμίζετε το στυλ του τίτλου κάθε υποενότητας
να έχει στυλ υποκεφαλίδας με δομημένη αρίθμηση, π.χ. 1.1, 1.2, 1.3, 2.1, 2.2, κοκ.
* Προσοχή στη στοίχιση των κειμένων των παραγράφων κάτω από τις κεφαλίδες και υποκεφαλίδες.
Καθορίζεται από τις επιλογές της «Παραγράφου», με μείωση ή αύξηση της εσοχής (indent).
* Οι τίτλοι των κεφαλαίων και υποενοτήτων πρέπει να έχουν στυλ επικεφαλίδων και υποκεφαλίδων,
ώστε να μπορεί να παραχθεί αυτόματα ο Πίνακας Περιεχομένων. Για κάθε νέα έκδοση του
κειμένου σας, κάνετε και ενημέρωση του Πίνακα Περιεχομένων.
* Το κείμενό σας πρέπει να χρησιμοποιεί σωστά τη σύνταξη και την ορθογραφία της γλώσσας
συγγραφής. Επίσης πρέπει να αποφεύγονται εκφράσεις του προφορικού λόγου ή της
(τεχνολογικής) Τέλος είναι προτιμότερο να χρησιμοποιείται παθητική φωνή αντί για ενεργητική και
να αποφεύγεται το 1ο
 πρόσωπο: αντί «Στην εργασία αυτή θα αναλύσω/αναλύσουμε …» προτιμήστε
το «Στην παρούσα εργασία θα αναλυθούν …».

### Εικόνες, φωτογραφίες, σχήματα, διαγράμματα:

* Οι εικόνες ή φωτογραφίες ή σχήματα ή διαγράμματα βοηθούν στην κατανόηση του περιεχομένου.
Μπορούν να εισαχθούν είτε μέσα στο κείμενο, κάτω από το σημείο του κειμένου όπου
αναφέρονται για πρώτη φορά, είτε σε Παράρτημα Εικόνων στο τέλος της εργασίας. Η δεύτερη
επιλογή προτιμάται όταν οι εικόνες είναι ανεξάρτητες από την κατανόηση του κειμένου.
* Καλό είναι να μην χρησιμοποιείται υπερβολικός αριθμός εικόνων, αλλά όσες είναι απαραίτητες για
την κατανόηση του κειμένου και την οπτικοποίηση λεπτών σημείων ή δύσκολων εννοιών.
* Αφού εισάγετε την εικόνα στο κατάλληλο σημείο του κειμένου, εισάγετε επίσης μία κενή γραμμή
πριν και μετά την εικόνα και ρυθμίζετε τις επιλογές της εικόνας ώστε να είναι in-line with text και
στοιχισμένη στο κέντρο.
* Κάτω από την εικόνα εισάγετε την λεζάντα (περιγραφή) της εικόνας και την αναφορά προέλευσης
(Πηγή) αν δεν την έχετε κατασκευάσει εσείς. Η λεζάντα αρχίζει με αρίθμηση, π.χ. Εικόνα 2.4: ….. και
είναι επίσης στοιχισμένη στο κέντρο.
* Όταν αναφέρεται μία εικόνα μέσα στο κείμενο, προηγείται πάντα η λέξη «Εικόνα», π.χ. “Στην
Εικόνα 2.1 εμφανίζεται ….”.
* Φροντίστε οι εικόνες πρέπει να είναι καλής ποιότητας και αρκετής ανάλυσης ώστε να είναι
ευκρινείς μέσα στο τελικό κείμενο.

### Εξισώσεις:

* Οι εξισώσεις δεν γράφονται με τον κειμενογράφο (π.χ., Word) αλλά δημιουργούνται με τον
επεξεργαστή εξισώσεων (π.χ., Equation Editor). Στην ίδια σειρά στο δεξιό περιθώριο εισάγεται και ο
αριθμός της εξίσωσης, μέσα σε παρένθεση, π.χ. (1), (2), κλπ.
* Αν οι εξισώσεις είναι πολλές και εμφανίζονται εξισώσεις σε περισσότερα κεφάλαια, είναι καλύτερο
να αριθμηθούν δομημένα εντός του κεφαλαίου, π.χ. (1.1), (1.2), (1.3), (2.1), (2.2), κοκ.
* Όταν αναφέρονται μέσα στο κείμενο, προηγείται πάντα η λέξη «Εξίσωση», π.χ. “Στην Εξίσωση (2.1)
χρησιμοποιήθηκε….”.

### Πίνακες:

* Οι πίνακες χρησιμοποιούνται ευρέως για την αποτύπωση τεχνικών χαρακτηριστικών,
αριθμητικών/ποσοτικών μεγεθών και αποτελεσμάτων.
* Φροντίστε οι πίνακες να είναι ευκρινείς και ευανάγνωστοι στο τελικό κείμενο. Ρυθμίστε το μέγεθος
της γραμματοσειράς όχι μικρότερο από 10 στιγμές.
* Οι πίνακες ρυθμίζονται όπως οι εικόνες (in-line-with-text, κέντρο, 1 κενή γραμμή πριν και μετά).
Πρέπει να υπάρχει πάντα εξωτερικό περίγραμμα (πλαίσιο), λεζάντα πίνακα με αρίθμηση, και
αναφορά στην πηγή, αν δεν τον έχετε κατασκευάσει εσείς. Η λεζάντα αρχίζει με αρίθμηση, π.χ.
Πίνακας 4.3: …. και βρίσκεται πάντα πάνω από τον πίνακα.

### Ειδικοί/τεχνικοί όροι:

Ειδικοί ή τεχνικοί όροι που εμφανίζονται στο κείμενο της ΔΕ μπορούν να γραφτούν είτε στην ελληνική
είτε στην αγγλική γλώσσα. Την πρώτη φορά που χρησιμοποιούνται, εισάγονται πρώτα στη γλώσσα που
είναι γραμμένη η ΔΕ (π.χ. ελληνικά) και δίπλα, σε παρένθεση, στην άλλη γλώσσα (π.χ. αγγλικά). Στη
συνέχεια χρησιμοποιείται η μία από τις δύο μορφές, συστηματικά. Το ίδιο ισχύει και για την χρήση
αρκτικόλεξων. Οι ειδικοί/τεχνικοί όροι πρέπει να εισαχθούν στο Αλφαβητικό Ευρετήριο Όρων μετά τον
Πίνακα Περιεχομένων.
